version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_absensi
    environment:
      POSTGRES_PASSWORD: habil123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_absensi_app
    environment:
      PGADMIN_DEFAULT_EMAIL: arlianasrori@gmail.com
      PGADMIN_DEFAULT_PASSWORD: habil123
    ports:
      - "5054:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
