from . import absen_model
from . import developer_model
from . import guru_mapel_model
from . import guru_walas_model
from . import jadwal_model
from . import notification_model
from . import petugas_BK_model
from . import sekolah_model
from . import siswa_model
from . import laporan_model
